version: '3'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: myapp/nginx
    container_name: webserver
    ports:
      - '80:80'
    volumes:
      - ../sem5_homework:/data/mysite.local
    networks:
      - app-network

  app:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: myapp/php
    container_name: app
    volumes:
      - ../sem5_homework:/data/mysite.local
    networks:
      - app-network

networks:
  app-network:
    driver: bridge